# Copyright 2019 Axel Huebl
#
# This file is part of WarpX.
#
# License: BSD-3-Clause-LBNL

# docs:
#   https://help.semmle.com/lgtm-enterprise/user/help/lgtm.yml-configuration-file.html#example-of-complete-lgtmyml-file

extraction:
  cpp:
    prepare:
      packages:
        - cmake
        - openmpi-bin
        - libopenmpi-dev
        - libhdf5-openmpi-dev
        - libadios-openmpi-dev
    after_prepare:
      - python -m pip install --upgrade pip
      - python -m pip install --upgrade wheel
      - python -m pip install --upgrade cmake
      - export CMAKE="$HOME/.local/bin/cmake"
    configure:
      command:
        - $CMAKE -S . -B build -DWarpX_OPENPMD=ON
    index:
      build_command:
        - $CMAKE --build build -j 2

