# Copyright 2018-2019 Axel Huebl, David Grote, Luca Fedeli
# Maxence Thevenet, Remi Lehe
#
# This file is part of WarpX.
#
# License: BSD-3-Clause-LBNL

dist: bionic
language: c++
sudo: true
cache: pip

env:
  global:
    - WARPX_CI_CCACHE=TRUE
    - WARPX_CI_OPENPMD=TRUE
  matrix:
    - WARPX_CI_REGULAR_CARTESIAN=TRUE
    - WARPX_CI_PSATD=TRUE
    - WARPX_CI_PYTHON_MAIN=TRUE
    - WARPX_CI_SINGLE_PRECISION=TRUE
    - WARPX_CI_RZ_OR_NOMPI=TRUE
    - WARPX_CI_QED=TRUE

before_install:
    - sudo apt-get update
    - sudo apt-get install -y ccache gcc gfortran g++ openmpi-bin libopenmpi-dev libfftw3-dev libfftw3-mpi-dev libhdf5-openmpi-dev pkg-config make python3 python3-pip python3-setuptools libblas-dev liblapack-dev
      # xenial misses "libadios-openmpi-dev"
    - sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 2
    - sudo update-alternatives --set python /usr/bin/python3

install:
    - python -m pip install --upgrade pip
    - python -m pip install --upgrade cmake matplotlib==3.2.2 mpi4py numpy scipy yt
    - export CEI_CMAKE="/home/travis/.local/bin/cmake"
    - export CEI_SUDO="sudo"
    - sudo curl -L -o /usr/local/bin/cmake-easyinstall https://git.io/JvLxY && sudo chmod a+x /usr/local/bin/cmake-easyinstall
    - if [ "${WARPX_CI_OPENPMD}" != "FALSE" ]; then
        cmake-easyinstall --prefix=/usr/local git+https://github.com/openPMD/openPMD-api.git
          -DopenPMD_USE_PYTHON=OFF -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF;
      fi
    - if [ "${WARPX_CI_RZ_OR_NOMPI:-FALSE}" == "TRUE" ]; then
        cmake-easyinstall --prefix=/usr/local git+https://bitbucket.org/icl/blaspp.git
          -DBLAS_LIBRARY=generic -DUSE_OPENMP=OFF -DBLASPP_BUILD_TESTS=OFF;
        cmake-easyinstall --prefix=/usr/local git+https://bitbucket.org/icl/lapackpp.git
          -DUSE_OPENMP=off -DLAPACKPP_BUILD_TESTS=OFF;
      fi

script:
    - export FFTW_HOME=/usr/
    - export BLASPP_HOME=/usr/local/
    - export LAPACKPP_HOME=/usr/local/
    - if [ -z ${WARPX_CI_OPENPMD} ]; then WARPX_CI_OPENPMD=TRUE; fi
    - if [ -z ${WARPX_CI_PSATD} ]; then WARPX_CI_PSATD=TRUE; fi

    # Run the tests on the current commit
    - export WARPX_TEST_COMMIT=$TRAVIS_COMMIT

    # Run the script that prepares the test environment and runs the tests
    - export OMP_NUM_THREADS=1
    - travis_wait 50 ./run_test.sh
