#!/usr/bin/env bash
#
# Copyright 2020 Axel Huebl
#
# License: BSD-3-Clause-LBNL

# search recursive inside a folder if a file contains tabs
#
# @result 0 if no files are found, else 1
#

set -eu -o pipefail

cd Docs

# treat all warnings as errors
echo "WARN_AS_ERROR = YES" >> Doxyfile

doxygen
