#!/usr/bin/env bash
#
# Copyright 2020 Axel Huebl
#
# License: BSD-3-Clause-LBNL

set -eu -o pipefail

cd Docs

curl -L -o amrex-doxygen-web.tag.xml \
  https://amrex-codes.github.io/amrex/docs_xml/doxygen/amrex-doxygen-web.tag.xml

# treat all warnings as errors
echo "WARN_AS_ERROR = YES" >> Doxyfile

doxygen
