#!/usr/bin/env bash

# Search input files in Examples/ and verify if all input files are tested

set -eu -o pipefail

ok=0

# all calls to add_warpx_test(...) in CMakeLists.txt files
registered_tests=$(grep -h -R -A5 "add_warpx_test" Examples/ | grep Examples)

# go through each input file: C++ inputs or PICMI Python
for file in $(find Examples -type f)
do
    # Name of file without path
    filename=$(basename $file)
    # If file is an input file
    if [[ ${filename:0:6 } =~ inputs       ]] ||
       [[ ${filename:0:12} =~ PICMI_inputs ]]
    then
        cr=$'$'
        file_cr="$file$cr"
        # Search file name in test list
        if [[ "${registered_tests,,}" != *"${file_cr}"* ]]
        then
            echo "$file is not tested!"
            ok=1
        fi
    fi
done

if [ $ok -ne 0 ]
then
    echo ""
    echo "All files in Examples that start with one of"
    echo " - inputs"
    echo " - PICMI_inputs"
    echo "must have an automated test."
    echo "Please add a test in Regression/WarpX-tests.ini"
    echo "for all files listed above."
fi

exit $ok
