#!/usr/bin/env bash

# Search input files in Examples/ and verify if all input files are tested

set -eu -o pipefail

ok=0

# all calls to add_warpx_test(...) in CMakeLists.txt files
registered_tests=$(grep -h -R -A5 "add_warpx_test" Examples/ | grep Examples)
# FIXME we should exclude tests whose line starts with '#' (test commented out)

# go through each input file
for file in $(find Examples -type f)
do
    # Name of file without path
    filename=$(basename $file)
    # If file is a test input file
    if [[ ${filename:0:11 } =~ inputs_test ]]
    then
        # Search file name in test list
        if [[ "${registered_tests}" != *"${file}"* ]]
        then
            echo "$file is not tested!"
            ok=1
        fi
    fi
done

if [ $ok -ne 0 ]
then
    echo ""
    echo "All files in Examples/ starting with 'inputs_test' must have an automated test."
    echo "Please add a test in the corresponding CMakeLists.txt for all files listed above."
fi

exit $ok
