#!/usr/bin/env bash
#
# Search inside Examples/ and check that file names start with
# inputs
# PICMI_inputs
# analysis
# README

set -eu -o pipefail

ok=0
files=()

for pathtofile in $(find Examples -type f)
do
    file=$(basename $pathtofile)
    if [[ ${file:0:14} != inputs_base_1d ]] &&
       [[ ${file:0:14} != inputs_base_2d ]] &&
       [[ ${file:0:14} != inputs_base_3d ]] &&
       [[ ${file:0:14} != inputs_base_rz ]] &&
       [[ ${file:0:14} != inputs_test_1d ]] &&
       [[ ${file:0:14} != inputs_test_2d ]] &&
       [[ ${file:0:14} != inputs_test_3d ]] &&
       [[ ${file:0:14} != inputs_test_rz ]] &&
       [[ ${file:0:8 } != analysis       ]] &&
       [[ ${file:  -4} != yaml           ]] &&
       [[ ${file:0:4 } != plot           ]] &&
       [[ ${file:0:6 } != README         ]] &&
       [[ ${file:0:10} != CMakeLists     ]]
    then
        files+=($file)
        echo "$pathtofile does not have a proper name!"
        ok=1
    fi
done

if [ $ok -ne 0 ]
then
    echo ""
    echo "Files in Examples/ must start with one of:"
    echo " - inputs_base_<1d;2d;3d;rz>: for base input files"
    echo " - inputs_test_<1d;2d;3d;rz>: for test input files"
    echo " - analysis                 : for analysis scripts"
    echo " - *.yaml                   : for third-party inputs, e.g., Ascent in-situ visualization"
    echo " - README                   : for README files"
    echo " - CMakeLists               : for CMake files"
    echo ""
    echo "Please rename the file(s) to comply, or move to another folder"
fi

exit $ok
