/* Copyright 2019-2022 Andrew Myers, Luca Fedeli, Maxence Thevenet,
 *                     Weiqun Zhang, Axel Huebl
 *
 * This file is part of WarpX.
 *
 * License: BSD-3-Clause-LBNL
 */
#ifndef WARPX_CONST_H_
#define WARPX_CONST_H_

#include <ablastr/constant.H>


namespace MathConst
{
    using namespace ablastr::constant::math;
}

namespace PhysConst
{
    using namespace ablastr::constant::SI;
}

#endif
