/* Copyright 2021 Luca Fedeli, Axel Huebl
 *
 * This file is part of WarpX.
 *
 * License: BSD-3-Clause-LBNL
 */

#ifndef WARPX_QUANTUM_SYNC_ENGINE_WRAPPER_FWD_H
#define WARPX_QUANTUM_SYNC_ENGINE_WRAPPER_FWD_H

class QuantumSynchrotronGetOpticalDepth;
class QuantumSynchrotronEvolveOpticalDepth;
class QuantumSynchrotronPhotonEmission;

class QuantumSynchrotronEngine;

#endif /* WARPX_QUANTUM_SYNC_ENGINE_WRAPPER_FWD_H */
