name: 🧹 clang-tidy

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-clangtidy
  cancel-in-progress: true

jobs:
  run_clang_tidy:
    name: clang-tidy
    runs-on: ubuntu-22.04
    if: github.event.pull_request.draft == false
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        .github/workflows/dependencies/clang14.sh
    - name: set up cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/ccache
        key: ccache-${{ github.workflow }}-${{ github.job }}-git-${{ github.sha }}
        restore-keys: |
             ccache-${{ github.workflow }}-${{ github.job }}-git-
    - name: build WarpX & run clang-tidy
      run: |
        export CCACHE_COMPRESS=1
        export CCACHE_COMPRESSLEVEL=10
        export CCACHE_MAXSIZE=300M
        export CCACHE_EXTRAFILES=${{ github.workspace }}/.clang-tidy
        export CCACHE_LOGFILE=${{ github.workspace }}/ccache.log.txt
        ccache -z

        export CXX=$(which clang++)
        export CC=$(which clang)

        cmake -S . -B build_clang_tidy \
          -DCMAKE_VERBOSE_MAKEFILE=ON  \
          -DWarpX_DIMS="1;2;3;RZ"      \
          -DWarpX_MPI=ON               \
          -DWarpX_COMPUTE=OMP          \
          -DWarpX_PSATD=ON             \
          -DWarpX_QED=ON               \
          -DWarpX_QED_TABLE_GEN=ON     \
          -DWarpX_OPENPMD=ON           \
          -DWarpX_PRECISION=SINGLE     \
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

        cmake --build build_clang_tidy -j 2

        ${{github.workspace}}/.github/workflows/source/makeMakefileForClangTidy.py --input ${{github.workspace}}/ccache.log.txt
        make -j2 --keep-going -f clang-tidy-ccache-misses.mak \
            CLANG_TIDY=clang-tidy \
            CLANG_TIDY_ARGS="--config-file=${{github.workspace}}/.clang-tidy --warnings-as-errors=*"

        ccache -s
        du -hs ~/.cache/ccache

  save_pr_number:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo $PR_NUMBER > pr_number.txt
      - uses: actions/upload-artifact@v3
        with:
          name: pr_number
          path: pr_number.txt
          retention-days: 1
